//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverwatchDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERT
    {
        public int alertID { get; set; }
        public Nullable<int> personID { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string dateTime { get; set; }
        public string status { get; set; }
        public Nullable<int> hotspotID { get; set; }
    }
}
