//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverwatchDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTSPOT
    {
        public int hotspotID { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string duration { get; set; }
        public string radius { get; set; }
        public Nullable<int> suburbID { get; set; }
        public Nullable<int> adminID { get; set; }
    }
}
