//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OverwatchDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAFEZONE
    {
        public int safezoneID { get; set; }
        public string longitude { get; set; }
        public string latidude { get; set; }
        public int suburbID { get; set; }
        public int adminID { get; set; }
    }
}
